/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mailscape;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.mail.MessagingException;
import javax.swing.DefaultListModel;
import javax.swing.text.Style;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import org.jsoup.Connection;
import java.sql.*;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import static mailscape.Get_Email.bodyList;
import static mailscape.Get_Email.fromList;
import static mailscape.Get_Email.subList;


/**
 *
 * @author laxmikanth
 */
public class get_detail extends javax.swing.JFrame implements MouseListener{
    String sub="";
    String body="";
    String fro="";
    int length=0;
    int index=0;
    String save="/home/laxmikanth/Downloads/";
    String USER="";
    String PASS="";
    String x="";

    /**
     * Creates new form get_detail
     */
    public get_detail(String s,String b,String c,int i,String user,String pass) throws MessagingException, ClassNotFoundException, SQLException {
        initComponents();
        this.sub=s;
        this.body=b;
        this.fro=c;
        this.index=i;
        this.USER=user;
        this.PASS=pass;
        Get_Email g=new Get_Email();
        jPanel2.addMouseListener(this);
        jPanel3.addMouseListener(this);
        if(body==null){
            body=" ";
        }
        jEditorPane1.setContentType("text/html");
        String text=body.replaceAll("<style([\\s\\S]+?)</style>","");
        x="<html><body>"+text+"</body></html>";
        jEditorPane1.setText(x);
        jTextArea1.setText(sub);
        StyleSheet css=((HTMLEditorKit)jEditorPane1.getEditorKit()).getStyleSheet();
        Style style=css.getStyle("body");
        jPanel2.setVisible(getList());
        jPanel3.setVisible(g.attachName("imap","imap.gmail.com","993",USER,PASS,index));
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(172, 185, 44));
        setMinimumSize(new java.awt.Dimension(1200, 830));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 246, 122));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 830));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 830));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 49, 11));
        jLabel4.setText("SUB:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, 40));

        jLabel3.setBackground(new java.awt.Color(247, 49, 11));
        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 49, 11));
        jLabel3.setText("BODY:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 120, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(248, 200, 151));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 680, 120));

        jEditorPane1.setEditable(false);
        jEditorPane1.setBackground(new java.awt.Color(248, 200, 151));
        jEditorPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jEditorPane1.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 720, 540));

        jLabel6.setFont(new java.awt.Font("Yrsa Medium", 0, 24)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 860, 340, 60));

        jPanel2.setBackground(new java.awt.Color(24, 132, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setBackground(new java.awt.Color(21, 124, 226));
        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel1.setText("STAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 740, 180, 100));

        jPanel3.setBackground(new java.awt.Color(21, 135, 249));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 36)); // NOI18N
        jLabel2.setText("ATTACHMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 740, 240, 90));

        jLabel5.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 860, 350, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1290, 1090));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(get_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(get_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(get_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(get_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    public void getLength() throws SQLException{
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection(Credentials.DB_URL,Credentials.USER,Credentials.pass);
            Statement stmt=con.createStatement();
            ResultSet count=stmt.executeQuery("Select count(*) from Star_Mail");
            while(count.next()){
                length=count.getInt("count(*)");
            }
            con.close();}
        catch(Exception event){System.out.println(event);}
        
            
    }
    public boolean getList() throws ClassNotFoundException, SQLException{
        getLength();
        DefaultListModel model=new DefaultListModel();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection(Credentials.DB_URL,Credentials.USER,Credentials.pass);
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("Select * from Star_Mail");
            
            String sub1[]=new String[length];
            String body1[]=new String[length];
            int i=0;
            while(rs.next()){
                sub1[i]=rs.getString(2);
                body1[i]=rs.getString(3);
                if(sub.equals(sub1[i])&&x.equals(body1[i])){
                    return false;
                }
                i++;
                
            }
            con.close();
        }
        catch(Exception event){
            System.out.println(event);
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent me) {
//         //To change body of generated methods, choose Tools | Templates.
         if(me.getSource()==jPanel2){
             try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                  java.sql.Connection con=DriverManager.getConnection(Credentials.DB_URL,Credentials.USER,Credentials.pass);
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("Select * from Star_Mail");
            x=x.replace("'", "\\'");
            String sqlInsert="INSERT INTO Star_Mail(name,sub,body)"+"VALUES('"+fro+"','"+sub+"','"+x+"')";
            int countInserted=stmt.executeUpdate(sqlInsert);
            if(countInserted!=0){
                jLabel5.setText("Email is starred successfully");
                jPanel2.setVisible(false);
            }
            con.close();
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(get_detail.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(get_detail.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
         if(me.getSource()==jPanel3){
             try {
                 Get_Email g=new Get_Email();
                 
                 jLabel6.setText("Downloading Attachment");
                 jLabel6.paintImmediately(jLabel6.getVisibleRect());
                 g.getAttach("imap","imap.gmail.com","993",USER,PASS,index);
                 jLabel6.setText("Attachment Downloaded");
                 jLabel6.paintImmediately(jLabel6.getVisibleRect());
                 
             } catch (MessagingException ex) {
                 Logger.getLogger(get_detail.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(get_detail.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
    }

    @Override
    public void mousePressed(MouseEvent me) {
      //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent me) {
         //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {}
}
